version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql.impact.dev
    hostname: mysql.impact.dev
    ports:
      - 33306:3306
    environment:
      TZ: Etc/UTC
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: impact
      MYSQL_USER: impact
      MYSQL_PASSWORD: impact
    restart: always
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - mysql_network

volumes:
  mysql_volume:
    driver: local

networks:
  mysql_network:
    driver: bridge
